media: 
  input: public/images
  output: images
content:
  - name: de-posts
    label: Posts (DE)
    type: collection
    path: src/content/blog/de
    fields: # The fields for each document, usually in front matter
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: heroImage, label: Cover Image, type: image }
      - { name: pubDate, label: Date, type: date }
      - { name: featured, label: Recommended Post, type: boolean}
      - name: category
        type: select
        label: Kategorie
        options:
            values: 
              - value: mietpreisbremse
                label: Mietpreisbremse
              - value: get_involved
                label: Aktiv werden
      - { name: body, label: Body, type: rich-text }
      
  - name: en-posts
    label: Posts (EN)
    type: collection
    path: src/content/blog/en
    fields: # The fields for each document, usually in front matter
      - { name: title, label: Title, type: string }
      - { name: description, label: Description, type: string }
      - { name: heroImage, label: Cover Image, type: image }
      - { name: pubDate, label: Date, type: date }
      - { name: featured, label: Recommended Post, type: boolean}
      - name: category
        type: select
        label: Kategorie
        options:
            values: 
              - value: mietpreisbremse
                label: Mietpreisbremse
              - value: get_involved
                label: Get Involved
      - { name: body, label: Body, type: rich-text }